# Step 1: Initial Data Exploration and Cleaning

In this notebook, we will load the NYC Yellow Taxi trip data for January 2025. Our goals are:
1.  Load the dataset.
2.  Perform an initial inspection of the data's structure, columns, and basic statistics.
3.  Identify and handle missing values.
4.  Filter out outliers and irrelevant data for our dispatching problem.
5.  Select the columns necessary for building our simulation environment.

In [1]:
import pandas as pd

# Load the dataset
file_path = 'data/yellow_tripdata_2025-01.parquet'
df = pd.read_parquet(file_path)

# Display the first few rows to get an overview
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
0,1,2025-01-01 00:18:38,2025-01-01 00:26:59,1.0,1.60,1.0,N,229,237,1,10.0,3.5,0.5,3.00,0.0,1.0,18.00,2.5,0.0,0.0
1,1,2025-01-01 00:32:40,2025-01-01 00:35:13,1.0,0.50,1.0,N,236,237,1,5.1,3.5,0.5,2.02,0.0,1.0,12.12,2.5,0.0,0.0
2,1,2025-01-01 00:44:04,2025-01-01 00:46:01,1.0,0.60,1.0,N,141,141,1,5.1,3.5,0.5,2.00,0.0,1.0,12.10,2.5,0.0,0.0
3,2,2025-01-01 00:14:27,2025-01-01 00:20:01,3.0,0.52,1.0,N,244,244,2,7.2,1.0,0.5,0.00,0.0,1.0,9.70,0.0,0.0,0.0
4,2,2025-01-01 00:21:34,2025-01-01 00:25:06,3.0,0.66,1.0,N,244,116,2,5.8,1.0,0.5,0.00,0.0,1.0,8.30,0.0,0.0,0.0

In [2]:
# Get a concise summary of the dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3475226 entries, 0 to 3475225
Data columns (total 20 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               int32
 1   tpep_pickup_datetime   datetime64[us]
 2   tpep_dropoff_datetime  datetime64[us]
 3   passenger_count        float64
 4   trip_distance          float64
 5   RatecodeID             float64
 6   store_and_fwd_flag     object
 7   PULocationID           int32
 8   DOLocationID           int32
 9   payment_type           int64
 10  fare_amount            float64
 11  extra                  float64
 12  mta_tax                float64
 13  tip_amount             float64
 14  tolls_amount           float64
 15  improvement_surcharge  float64
 16  total_amount           float64
 17  congestion_surcharge   float64
 18  Airport_fee            float64
 19  cbd_congestion_fee     float64
dtypes: datetime64[us](2), float64(13), int32(3), int64(1), object(1)
memory usage: 490.5+ MB

In [3]:
# Generate descriptive statistics
df.describe()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
count,3.475226e+06,3475226,3475226,2.935077e+06,3.475226e+06,2.935077e+06,3.475226e+06,3.475226e+06,3.475226e+06,3.475226e+06,3.475226e+06,3.475226e+06,3.475226e+06,3.475226e+06,3.475226e+06,3.475226e+06,2.935077e+06,2.935077e+06,3.475226e+06
mean,1.785428e+00,2025-01-17 11:02:55.910964,2025-01-17 11:17:56.997901,1.297859e+00,5.855126e+00,2.482535e+00,1.651916e+02,1.641252e+02,1.036623e+00,1.708180e+01,1.317737e+00,4.780991e-01,2.959813e+00,4.493081e-01,9.547946e-01,2.561129e+01,2.225237e+00,1.239111e-01,4.834093e-01
min,1.000000e+00,2024-12-31 20:47:55,2024-12-18 07:52:40,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,-9.000000e+02,-7.500000e+00,-5.000000e-01,-8.600000e+01,-1.269400e+02,-1.000000e+00,-9.010000e+02,-2.500000e+00,-1.750000e+00,-7.500000e-01
25%,2.000000e+00,2025-01-10 07:59:01,2025-01-10 08:15:29.500000,1.000000e+00,9.800000e-01,1.000000e+00,1.320000e+02,1.130000e+02,1.000000e+00,8.600000e+00,0.000000e+00,5.000000e-01,0.000000e+00,0.000000e+00,1.000000e+00,1.520000e+01,2.500000e+00,0.000000e+00,0.000000e+00
50%,2.000000e+00,2025-01-17 15:41:33,2025-01-17 15:59:34,1.000000e+00,1.670000e+00,1.000000e+00,1.620000e+02,1.620000e+02,1.000000e+00,1.211000e+01,0.000000e+00,5.000000e-01,2.450000e+00,0.000000e+00,1.000000e+00,1.995000e+01,2.500000e+00,0.000000e+00,7.500000e-01
75%,2.000000e+00,2025-01-24 19:34:06,2025-01-24 19:48:31,1.000000e+00,3.100000e+00,1.000000e+00,2.340000e+02,2.340000e+02,1.000000e+00,1.950000e+01,2.500000e+00,5.000000e-01,3.930000e+00,0.000000e+00,1.000000e+00,2.778000e+01,2.500000e+00,0.000000e+00,7.500000e-01
max,7.000000e+00,2025-02-01 00:00:44,2025-02-01 23:44:11,9.000000e+00,2.764236e+05,9.900000e+01,2.650000e+02,2.650000e+02,5.000000e+00,8.633721e+05,1.500000e+01,1.050000e+01,4.000000e+02,1.709400e+02,1.000000e+00,8.633804e+05,2.500000e+00,6.750000e+00,7.500000e-01
std,4.263282e-01,NaN,NaN,7.507503e-01,5.646016e+02,1.163277e+01,6.452948e+01,6.940169e+01,7.013334e-01,4.634729e+02,1.861509e+00,1.374623e-01,3.779681e+00,2.002582e+00,2.781938e-01,4.636585e+02,9.039932e-01,4.725090e-01,3.619307e-01

#### Key Observations from Initial Exploration
1. __Timestamps are Objects__: tpep_pickup_datetime and tpep_dropoff_datetime are indeed loaded as actual dates. Ergo, we can perform time-based calculations with them in this state.
2. __Passenger Count__: The minimum passenger_count is 0. Trips with no passengers are not relevant to our dispatching problem.
3. __Trip Distance__: The minimum trip_distance is 0. These could be cancelled trips or data errors. A taxi moving 0 distance is not a useful trip to model.
4. __Trip Duration (Implicit)__: The describe() output shows some potentially problematic trip durations. For example, the maximum trip_duration is likely very high, representing outliers. We need to calculate this field to be sure.
5. __Fare Amount__: The minimum fare_amount can be negative or zero, which represents disputes, cancellations, or errors. We should only consider trips with a positive fare.

### Step 2.1: Data Cleaning and Filtering

Based on the initial exploration, I need to clean the data. I will remove outliers and invalid data points. Here's what the cells below do:

1. __Calculate Trip Duration__: I first calculate the `trip_duration` in minutes. This is a crucial feature for filtering.
2. __Apply Filters__: Then, I filter the DataFrame to keep only the trips that are useful for our model:
    - Trip duration between 1 and 60 minutes. This removes both extremely short, likely erroneous trips and very long trips that are outliers.
    - trip_distance greater than 0.
    - passenger_count greater than 0.
    - fare_amount greater than 0.
3. __Post-Cleaning Analysis__: Finally, I run info() and describe() again on the new, filtered DataFrame (df_filtered).

In [10]:
# # Convert to datetime objects - Not neded as they are already in datetime format
# df['tpep_pickup_datetime'] = pd.to_datetime(df['tpep_pickup_datetime'])
# df['tpep_dropoff_datetime'] = pd.to_datetime(df['tpep_dropoff_datetime'])

# Calculate trip duration in minutes
df['trip_duration'] = (df['tpep_dropoff_datetime'] - df['tpep_pickup_datetime']).dt.total_seconds() / 60

# Display the first few rows with the new column
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,...,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee,trip_duration
0,1,2025-01-01 00:18:38,2025-01-01 00:26:59,1.0,1.60,1.0,N,229,237,1,...,3.5,0.5,3.00,0.0,1.0,18.00,2.5,0.0,0.0,8.350000
1,1,2025-01-01 00:32:40,2025-01-01 00:35:13,1.0,0.50,1.0,N,236,237,1,...,3.5,0.5,2.02,0.0,1.0,12.12,2.5,0.0,0.0,2.550000
2,1,2025-01-01 00:44:04,2025-01-01 00:46:01,1.0,0.60,1.0,N,141,141,1,...,3.5,0.5,2.00,0.0,1.0,12.10,2.5,0.0,0.0,1.950000
3,2,2025-01-01 00:14:27,2025-01-01 00:20:01,3.0,0.52,1.0,N,244,244,2,...,1.0,0.5,0.00,0.0,1.0,9.70,0.0,0.0,0.0,5.566667
4,2,2025-01-01 00:21:34,2025-01-01 00:25:06,3.0,0.66,1.0,N,244,116,2,...,1.0,0.5,0.00,0.0,1.0,8.30,0.0,0.0,0.0,3.533333

In [11]:
# Get the original number of rows
original_rows = len(df)

# Apply filters
df_filtered = df[
    (df['trip_duration'] >= 1) & (df['trip_duration'] <= 60) &
    (df['trip_distance'] > 0) &
    (df['passenger_count'] > 0) &
    (df['fare_amount'] > 0)
].copy()

# Get the number of rows after filtering
filtered_rows = len(df_filtered)

print(f"Original number of trips: {original_rows}")
print(f"Number of trips after filtering: {filtered_rows}")
print(f"Percentage of data removed: {((original_rows - filtered_rows) / original_rows) * 100:.2f}%")

Original number of trips: 3475226
Number of trips after filtering: 2777025
Percentage of data removed: 20.09%

### Step 2.2: Post-Cleaning Analysis

Let's re-examine the data to see the effect of our cleaning operations. The statistics should now look much more reasonable.

In [6]:
# Display a concise summary of the filtered dataframe
df_filtered.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2777025 entries, 0 to 2935076
Data columns (total 21 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               int32
 1   tpep_pickup_datetime   datetime64[us]
 2   tpep_dropoff_datetime  datetime64[us]
 3   passenger_count        float64
 4   trip_distance          float64
 5   RatecodeID             float64
 6   store_and_fwd_flag     object
 7   PULocationID           int32
 8   DOLocationID           int32
 9   payment_type           int64
 10  fare_amount            float64
 11  extra                  float64
 12  mta_tax                float64
 13  tip_amount             float64
 14  tolls_amount           float64
 15  improvement_surcharge  float64
 16  total_amount           float64
 17  congestion_surcharge   float64
 18  Airport_fee            float64
 19  cbd_congestion_fee     float64
 20  trip_duration          float64
dtypes: datetime64[us](2), float64(14), int32(3), int64(1), object(1)
memory usage: 434.3+ MB

In [7]:
# Display descriptive statistics for the filtered dataframe
df_filtered.describe()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee,trip_duration
count,2.777025e+06,2777025,2777025,2.777025e+06,2.777025e+06,2.777025e+06,2.777025e+06,2.777025e+06,2.777025e+06,2.777025e+06,2.777025e+06,2.777025e+06,2.777025e+06,2.777025e+06,2.777025e+06,2.777025e+06,2.777025e+06,2.777025e+06,2.777025e+06,2.777025e+06
mean,1.778795e+00,2025-01-17 02:23:13.715712,2025-01-17 02:37:15.522531,1.306043e+00,3.058211e+00,2.075076e+00,1.674076e+02,1.663864e+02,1.172878e+00,1.768262e+01,1.600138e+00,4.964251e-01,3.456387e+00,4.861674e-01,9.905172e-01,2.704442e+01,2.339708e+00,1.261121e-01,4.900756e-01,1.403011e+01
min,1.000000e+00,2024-12-31 20:47:55,2024-12-31 20:54:00,1.000000e+00,1.000000e-02,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e-02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.010000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
25%,2.000000e+00,2025-01-09 16:22:20,2025-01-09 16:36:45,1.000000e+00,9.900000e-01,1.000000e+00,1.320000e+02,1.170000e+02,1.000000e+00,8.600000e+00,0.000000e+00,5.000000e-01,1.480000e+00,0.000000e+00,1.000000e+00,1.590000e+01,2.500000e+00,0.000000e+00,0.000000e+00,7.066667e+00
50%,2.000000e+00,2025-01-16 21:07:41,2025-01-16 21:20:41,1.000000e+00,1.610000e+00,1.000000e+00,1.620000e+02,1.630000e+02,1.000000e+00,1.210000e+01,1.000000e+00,5.000000e-01,2.900000e+00,0.000000e+00,1.000000e+00,2.022000e+01,2.500000e+00,0.000000e+00,7.500000e-01,1.128333e+01
75%,2.000000e+00,2025-01-24 17:33:07,2025-01-24 17:47:49,1.000000e+00,2.940000e+00,1.000000e+00,2.340000e+02,2.360000e+02,1.000000e+00,1.910000e+01,2.500000e+00,5.000000e-01,4.210000e+00,0.000000e+00,1.000000e+00,2.805000e+01,2.500000e+00,0.000000e+00,7.500000e-01,1.786667e+01
max,2.000000e+00,2025-02-01 00:00:44,2025-02-01 00:42:38,9.000000e+00,3.358890e+04,9.900000e+01,2.650000e+02,2.650000e+02,4.000000e+00,8.633721e+05,1.500000e+01,6.500000e+00,4.000000e+02,1.269400e+02,1.000000e+00,8.633804e+05,2.500000e+00,1.750000e+00,7.500000e-01,6.000000e+01
std,4.150581e-01,NaN,NaN,7.417187e-01,2.077402e+01,9.948771e+00,6.293882e+01,6.877375e+01,4.727029e-01,5.183175e+02,1.889500e+00,4.246455e-02,3.654702e+00,2.002352e+00,9.691692e-02,5.184661e+02,6.124024e-01,4.525393e-01,3.569071e-01,1.000751e+01

### Step 3: Preparing Location Data

Our goal is to use the official NYC Taxi Zones as our discrete locations. This requires us to:
1. Download the taxi zone lookup table.
2. Filter our trip data to a specific, high-density area. We will choose Manhattan as it has the highest volume of taxi trips.
3. Save the final, cleaned dataset for use in our simulation.

Upon inspecting the columns from `df.info()`, we can see `PULocationID` and `DOLocationID`. These are not arbitrary numbers; they correspond to the official NYC Taxi Zones. The city is already divided into meaningful zones like "JFK Airport," "Midtown Center," etc. Using these official zones is far superior to creating our own grid for several reasons:

- __Real-World Relevance__: These zones are used in official city planning and analysis.
- __Simplicity__: It saves us the complex and often arbitrary task of creating our own geographical grid.
- __Richness__: We can get the borough and zone names for each ID, which is invaluable for analysis.

My task, then, is not to create a discretization, but to utilize the existing one. I need to download the lookup table that maps these IDs to their corresponding Borough and Zone names. This will allow us to understand the data better and, importantly, to filter our simulation to a specific area, like Manhattan, where ride-hailing is most dense.

The cells below are set to handle this. Here is the plan for these new cells:

1. __Download Taxi Zone Lookup Table__: A cell will download the `taxi_zone_lookup.csv` file directly into the `data` directory.
2. __Load and Inspect Lookup Table__: I will load this CSV into a new DataFrame and inspect it.
3. __Filter for Manhattan__: For my simulation, focusing on a dense, contiguous area is a good starting point. I will filter the main dataset to include only trips that start and end within Manhattan. This reduces complexity and focuses the agent on the most active region.
4. __Save Cleaned Data__: Finally, I will save this fully cleaned and filtered DataFrame to a new Parquet file. This is a critical step, as it creates a checkpoint. After this checkpoint, the user won't have to re-run all the cleaning steps every time the user works on the project.

In [13]:
import os
import requests

# Download the taxi zone lookup table
lookup_url = 'https://d37ci6vzurychx.cloudfront.net/misc/taxi_zone_lookup.csv'
lookup_filepath = 'data/taxi_zone_lookup.csv'

if not os.path.exists(lookup_filepath):
    print('Downloading taxi zone lookup table...')
    response = requests.get(lookup_url)
    with open(lookup_filepath, 'wb') as f:
        f.write(response.content)
    print('Download complete.')
else:
    print('Taxi zone lookup table already exists.')

# Load the lookup table
df_zones = pd.read_csv(lookup_filepath)
df_zones.head()

Taxi zone lookup table already exists.

   LocationID        Borough                     Zone service_zone
0           1            EWR           Newark Airport          EWR
1           2         Queens              Jamaica Bay    Boro Zone
2           3          Bronx  Allerton/Pelham Gardens    Boro Zone
3           4      Manhattan            Alphabet City  Yellow Zone
4           5  Staten Island            Arden Heights    Boro Zone

Now I will filter my dataset to only include trips that start and end in Manhattan.

In [16]:
# Get the LocationIDs for Manhattan
manhattan_zones = df_zones[df_zones['Borough'] == 'Manhattan']['LocationID'].tolist()

# Filter the trips
original_rows = len(df_filtered)
df_manhattan = df_filtered[
    df_filtered['PULocationID'].isin(manhattan_zones) &
    df_filtered['DOLocationID'].isin(manhattan_zones)
].copy()
filtered_rows = len(df_manhattan)

print(f"Number of trips before Manhattan filter: {original_rows}")
print(f"Number of trips after Manhattan filter: {filtered_rows}")
print(f"Percentage of data remaining: {(filtered_rows / original_rows) * 100:.2f}%")

Number of trips before Manhattan filter: 2777025
Number of trips after Manhattan filter: 2385573
Percentage of data remaining: 85.90%

Finally, let's save our processed data to a new file. This will be the input for the next notebook where I will build the simulation environment.

In [17]:
# Save the cleaned and filtered data
output_filepath = 'data/yellow_tripdata_2025-01_manhattan.parquet'
df_manhattan.to_parquet(output_filepath)

print(f"Cleaned data saved to {output_filepath}")
print(f"This concludes our data exploration and cleaning phase.")

Cleaned data saved to data/yellow_tripdata_2025-01_manhattan.parquet
This concludes our data exploration and cleaning phase.